---
language: python
python:
  - "3.8"

install:
  - pip install numpy scipy matplotlib gsw munch pdoc3 requests
  - pip install .

script:
  - rm -rf docs
  - mkdir docs
  - pdoc --html --force --config latex_math=True gvpy
  - mv ./html/gvpy/*.html ./docs/
  - rm -rf ./html

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    target_branch: gh-pages
    on:
      branch: master
