name: gvpy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - cartopy
  - cmocean
  - dask
  - dask-core
  - gsw
  - yaml
  - flake8
  - matplotlib
  - munch
  - numpy
  - pandas
  - pandoc
  - python
  - pytest
  - scipy
  - tqdm
  - xarray
  - xgcm
  - pdoc
  - pip
  - pip:
    - pyrsktools
    - lat-lon-parser
    # - seabird
    - watchmagic
    - jupytext
    # - mixsea
    # - "git+https://github.com/modscripps/mixsea@main"
    - "-e ."
