name: gvpy
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipympl
  - ipdb
  - black
  - isort
  - cartopy
  - cmocean
  - dask
  - dask-core
  - gsw
  - ipykernel
  - ipython
  - ipywidgets
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - yaml
  - flake8
  - pyqt5
  - matplotlib
  - munch
  - nbconvert
  - nbformat
  - netcdf4
  - numpy
  - pandas
  - pandoc
  - python
  - pytest
  - scipy
  - tqdm
  - xarray
  - xgcm
  - pdoc3
  - pip
  - pip:
    - pyrsktools
    - seabird
    - watchmagic
    - jupytext
    - mixsea
    - "-e /Users/gunnar/Projects/python/gvpy"
