name: gvpy
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cartopy
  - cmocean
  - dask
  - dask-core
  - gsw
  - yaml
  - flake8
  - matplotlib
  - munch
  - netcdf4
  - numpy
  - pandas
  - pandoc
  - python
  - pytest
  - scipy
  - tqdm
  - xarray
  - xgcm
  - pdoc3
  - pip
  - pip:
    - pyrsktools
    - lat-lon-parser
    - seabird
    - watchmagic
    - jupytext
    - mixsea
    - "-e ."
