[build-system]
requires = ["uv_build>=0.8.22,<0.10.0"]
build-backend = "uv_build"

[project]
name = "gvpy"
version = "2025.11"
authors = [
    {name = "Gunnar Voet", email = "gvoet@ucsd.edu"},
    ]
description = "Library of python modules for data analysis and visualization"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["physical oceanography"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Oceanography",
    ]
requires-python = ">= 3.11"
dependencies = [
    "numpy",
    "matplotlib>=3.10",
    "xarray",
    "netcdf4",
    "scipy",
    "gsw",
    "dask",
    "cartopy",
    "munch",
    "pandas",
    "IPython",
    "requests",
    "mixsea>=0.2",
    "lat-lon-parser",
    "loguru",
    "ipynbname",
    ]

[project.urls]
Homepage = "https://github.com/gunnarvoet/gvpy"
Documentation = "https://gunnarvoet.github.io/gvpy/gvpy.html"
Repository = "https://github.com/gunnarvoet/gvpy.git"
Issues = "https://github.com/gunnarvoet/gvpy/issues"

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
    "pytest>=9.0.1",
    "ruff>=0.14.5",
]

[tool.uv.sources]
mixsea = { git = "https://github.com/modscripps/mixsea", branch = "main" }

[tool.pytest.ini_options]
# in general, do not place a `__init__.py` in your tests
# options are explained here:
# https://learn.scientific-python.org/development/guides/pytest/
minversion = "6.0"
# addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
addopts = []
xfail_strict = true
filterwarnings = ["error"]
log_cli_level = "info"
testpaths = [
    "tests/",
    ]
